apiVersion: apps/v1
kind: Deployment
metadata:
  name: hirehawk-user-deployment
  labels:
    app: hirehawk-user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hirehawk-user
  template:
    metadata:
      labels:
        app: hirehawk-user
    spec:
      containers:
      - name: hirehawk-user
        image: pavel98volk/hirehawk:user
        ports:
        - containerPort: 8200
