apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hirehawk-user-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /user/*
        backend:
          serviceName: hirehawk-user-deployment
          servicePort: 8200
